// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADfOEHDdN7TrxQZhWUwdE3BavEY8-KQUc',
    appId: '1:403011738347:web:1654822d0412a70aae7cae',
    messagingSenderId: '403011738347',
    projectId: 'nim-flutterfire',
    authDomain: 'nim-flutterfire.firebaseapp.com',
    storageBucket: 'nim-flutterfire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9NQy6W46Ue5rRMMxKWIgkJ4elrkxHvVY',
    appId: '1:403011738347:android:3016712562724794ae7cae',
    messagingSenderId: '403011738347',
    projectId: 'nim-flutterfire',
    storageBucket: 'nim-flutterfire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIRpGYwzsJyaTmf475QiQ1N6WVnw8T8Ek',
    appId: '1:403011738347:ios:d12cffe1f94355eaae7cae',
    messagingSenderId: '403011738347',
    projectId: 'nim-flutterfire',
    storageBucket: 'nim-flutterfire.appspot.com',
    iosBundleId: 'com.example.nimFlutter',
  );
}
